# WireGuard Enterprise Configuration
# This configuration file defines the enterprise deployment

# Web Interface Configuration
web_interface:
  host: "0.0.0.0"
  port: 5000
  ssl: true
  cert_path: "/etc/wireguard/certs/server.crt"
  key_path: "/etc/wireguard/certs/server.key"

# Monitoring Configuration
monitoring:
  metrics_port: 9090
  collection_interval: 30
  retention_days: 30
  alert_thresholds:
    cpu_usage: 80
    memory_usage: 90
    connection_count: 1000

# Cloud Deployment
cloud:
  - provider: "aws"
    name: "wireguard-prod-1"
    region: "us-east-1"
    instance_type: "t3.micro"
    ami_id: "ami-0c55b159cbfafe1f0"
    wireguard_config: |
      [Interface]
      PrivateKey = <private_key>
      Address = 10.0.0.1/24
      ListenPort = 51820
      
  - provider: "gcp"
    name: "wireguard-prod-2"
    project_id: "my-project"
    zone: "us-central1-a"
    machine_type: "e2-micro"
    image: "ubuntu-2004-focal-v20220419"
    
  - provider: "azure"
    name: "wireguard-prod-3"
    location: "eastus"
    resource_group: "wireguard-rg"
    vm_size: "Standard_B1s"
    admin_username: "wireguard"

# Container Deployment
containers:
  - platform: "docker"
    name: "wireguard-docker-1"
    config_path: "/etc/wireguard/docker/wg0.conf"
    
  - platform: "kubernetes"
    name: "wireguard-k8s-1"
    namespace: "wireguard"
    config_path: "/etc/wireguard/k8s/wg0.conf"
    replicas: 1

# Security Configuration
security:
  api_key: "${WIREGUARD_API_KEY}"
  allowed_ips:
    - "10.0.0.0/8"
    - "192.168.0.0/16"
  firewall_rules:
    - port: 51820
      protocol: "udp"
      allowed_sources: ["0.0.0.0/0"]
    - port: 5000
      protocol: "tcp"
      allowed_sources: ["10.0.0.0/8"]

# Logging Configuration
logging:
  level: "INFO"
  file: "/var/log/wireguard/enterprise.log"
  max_size: "100M"
  backup_count: 10